controllers:
  main:
    replicas: 2
    containers:
      main:
        image:
          repository: ghcr.io/ictu/pseudoniemenservice
          tag: latest
        probes:
          liveness:
            httpGet:
              path: /actuator/health/liveness
              port: 9080
          readiness:
            httpGet:
              path: /actuator/health/readiness
              port: 9080
          startup:
            enabled: true
            spec:
              initialDelaySeconds: 5
              timeoutSeconds: 3
              periodSeconds: 5
              failureThreshold: 5
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          limits:
            cpu: 1
            memory: 612Mi
          requests:
            cpu: 1
            memory: 612Mi
        env:
          SPRING_PROFILES_ACTIVE: production
          pseudoniemenservice_token-private-key: i4dfBykN5Fjw9p3ADxvpRUhpbFSXepRSOcRGuaiJ4iQ= # test key
service:
  main:
    controller: main
    ports:
      http:
        port: 8080

ingress:
  main:
    className: nginx
    annotations:
      external-dns.alpha.kubernetes.io/target: ingress.stelseltoegang.nl
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: pseudoniemenservice.stelseltoegang.nl
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - secretName: pseudoniemenservice.stelseltoegang.nl
        hosts:
          - pseudoniemenservice.stelseltoegang.nl
